name: doc_scan_flutter
description: "A Flutter plugin for scanning documents with automatic edge detection, cropping, and enhancement. Uses ML Kit on Android and VisionKit on iOS for high-quality scans."
version: 1.0.5
homepage: https://github.com/Ideeri/doc_scan
repository: https://github.com/Ideeri/doc_scan.git
issue_tracker: https://github.com/Ideeri/doc_scan/issues

topics:
  - document-scanner
  - pdf-scanner
  - flutter-plugin
  - visionkit
  - mlkit

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fr.ideeri.doc_scan
        pluginClass: DocScanPlugin
      ios:
        pluginClass: DocScanPlugin
